name: Mobster
main: com.blockempires.mobster.MobsterPlugin
version: 0.3
depend: [WorldGuard]
softdepend: [Heroes]
commands:
    mobster:
        description: Configure Mobster
        usage: /mobster [room|dungeon|spawn]

permissions:
    mobster.edit:
        description: Allows you to use Mobster commands
        default: false
    